version: "3.8"
services:
  python:
    container_name: frontend
    image: frontend/node:20
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    ports:
      - 9000:9000
    deploy:
        restart_policy:
            condition: on-failure
    volumes:
      - ./:/mnt/frontend
